version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        exclude-patterns:
          - "rubocop*"
        update-types:
          - "minor"
          - "patch"
      rubocop:
        patterns:
          - "rubocop*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
